webtalk_init -webtalk_dir D:/MIPSCPU/MIPSCPU.sim/sim_1/behav/xsim/xsim.dir/mips_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jan  7 15:49:09 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "652ddd93-c516-4e92-9675-94f4b7abe851" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5e56f309fc344d20bf963fe5dbb3a1d9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "104" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12500H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3110 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "8 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8564_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1984439269 -regid "" -xml D:/MIPSCPU/MIPSCPU.sim/sim_1/behav/xsim/xsim.dir/mips_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/MIPSCPU/MIPSCPU.sim/sim_1/behav/xsim/xsim.dir/mips_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/MIPSCPU/MIPSCPU.sim/sim_1/behav/xsim/xsim.dir/mips_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
