# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/MIPSCPU/MIPSCPU.cache/wt [current_project]
set_property parent.project_path D:/MIPSCPU/MIPSCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/MIPSCPU/MIPSCPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/ControlSignalDefine.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/ALU.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/AluSrcA.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/BranchTest.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/CPU.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/ControlUnit.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/DataMemory.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/EX_MEM.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/Forwarding.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/HazardDetection.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/ID_EX.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/IF_ID.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/InstructionMemory.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/MEM_WB.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/MUX2.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/MUX4.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/MemDataExtension.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/NextPC.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/PC.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/Register.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/SHOW_ON_LED.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/SignExtension.v
  D:/MIPSCPU/MIPSCPU.srcs/sources_1/new/MIPS_CPU.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/MIPSCPU/MIPSCPU.srcs/constrs_1/imports/EGo1-引脚约束文件/EGo1.xdc
set_property used_in_implementation false [get_files D:/MIPSCPU/MIPSCPU.srcs/constrs_1/imports/EGo1-引脚约束文件/EGo1.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top MIPS_CPU -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MIPS_CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MIPS_CPU_utilization_synth.rpt -pb MIPS_CPU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
